### ISSUE TITLE
Coding style in general

### ISSUE THREAD

**Issue by TMMeijers** [essamalsaloum/for-Homework#12]
There are some points which could be better:
*josn.js*:
- lines 66-88 the indentation of the for loop is wrong.
- variable names could be (way) better: `objects` for the movie response could be `movieResponse` (or something else, there is no correct way, just better ways ;)). Also don't abbreviate words that have no common abbreviation. `Ls` for List is not very clear.

*style.css*:
- Use spaces after your css selectors. So `a {` and not `a{`.

*arrayfiltermethod.js*:
- File name: use camel case (arrayFilterMethod)
- When you use a forEach and other things that accept a callback, put the content of the function on the next line, as well as the closing accolades etc.
- Forgot enclosing accolades for the last for loop (as well as spacing). 

*general*:
- Typo's in your files and file names. Also we discussed this, but josn.js is not a good name for your script. It tells us nothing about what it does. The fact that it has a typo makes it worse :p
- Comments your functions so other people know what parameters they need, what they do and what they return. This also makes it so you functions are seperated visually, removing the need for your one line comments `//------------------------`
- Remove debugging statements. Once you know a function works you can remove certain console.logs, as they don't add anything but they do clutter your console. Also once you deploy it (hand the homework in ;)) your customer (me) sees these things and that is totally unnecessary.

**Comment by essamalsaloum** [comment]
Everything that was mentioned in the issue was resolved
