### ISSUE TITLE
arrayfiltermethod.js

### ISSUE THREAD

**Issue by TMMeijers** [essamalsaloum/for-Homework#13]
Some tips:
- When you construct the hashmap (object) to see which is already present. If you say `j` could be any number, why increase it? Best would be to just assign `true` to it ;)
- To pretty print your output you could make a helper function in a script at the top level of your repo which takes a string (or array of strings?) and outputs it between seperating lines or something. That way you don't clutter your code :)

**Comment by essamalsaloum** [comment]
Done by assign `true` to `j`
